unique_ids:
  forms:
    Home: '1687266336075951822278990.3427'
    HomePage: TUOTCOGBX262WAKNFDX7WF35RJS6FNKA
    Main: '1687266325069404055233867.3924'
  modules: {}
  server_modules: {}
  assets:
    standard-page.html: ULAFXLR62IBSMWBMN5E4AXJFXJAZHFUQ
    theme.css: SR2LRINPICQWJX2Z5UORSTTI3A2ABTBW
    your-logo-here-low-resolution-logo-color-on-transparent-background.png: '1687182225622929593686151.4889'
